In [4]:
import numpy as np 
import pandas as pd

# Numpy 

## Zadanie - indeksowanie

In [5]:
A = np.arange(1,16).reshape(3,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
A[1]

array([ 6,  7,  8,  9, 10])

In [7]:
A[:,3]

array([ 4,  9, 14])

In [8]:
A[1:,3:]

array([[ 9, 10],
       [14, 15]])

## Zad 1 

In [9]:
def dzialanie(a,b): 
    """
    a,b - ndarray
    out - zwracana lista, lub komunikat o błędzie 
    """
    # podpowiedź: jako funkcji cos() użyj np.cos(ndarray), a jako pi np.pi
    
    #=======================================Twoj kod=======================================

    out = ((a**2 + b **3)**b - np.cos(np.pi*a))/10

    #======================================================================================
    
    return out

In [10]:
# nie zmieniać kodu!
a = np.array([3,2,1])
b = np.array([1,1,2])

dzialanie(a,b)

array([1.1, 0.4, 8.2])

## Zad 2

In [11]:
def dzialanie2(A,B): 
    """
    A, B - 1d arrays
    """
    #===============================================Twój kod======================================================
    A, B = A.reshape(4,5), B.reshape(4,5)
    
    A[:,2] *= B[3].sum()
    A[:,3] = B[:,4] * -1
    
    C = A
    
    C[::2] *= 2
    
    #================================================koniec========================================================
    
    return C

In [12]:
# nie zmieniać kodu!
A = np.arange(1,21)
B = np.arange(20,40)

dzialanie2(A,B)

array([[   2,    4, 1110,  -48,   10],
       [   6,    7, 1480,  -29,   10],
       [  22,   24, 4810,  -68,   30],
       [  16,   17, 3330,  -39,   20]])

# Pandas 

## Zadanie - procenty

In [13]:
df = pd.read_csv("https://raw.githubusercontent.com/R-Ladies-Warsaw/PoweR/master/Cz%C4%99%C5%9B%C4%87%202%20-%20Formatowanie%20danych/Python/data/vgsales.csv", delimiter= ",").dropna().reset_index(drop=True).drop("Rank", axis = 1)

In [15]:
df.loc[df.EU_Sales > df.NA_Sales].Name.count() / df.Name.count() * 100

15.014425142716837

## Zad 1 

In [20]:
df.loc[(df.Platform == "PS3") & (df.EU_Sales > df.NA_Sales)]

Name Platform    Year      Genre  \
16                 Grand Theft Auto V      PS3  2013.0     Action   
34         Call of Duty: Black Ops II      PS3  2012.0    Shooter   
37     Call of Duty: Modern Warfare 3      PS3  2011.0    Shooter   
54                     Gran Turismo 5      PS3  2010.0     Racing   
82                     FIFA Soccer 13      PS3  2012.0     Action   
...                               ...      ...     ...        ...   
15889            Resistance Dual Pack      PS3  2011.0    Shooter   
15919   Tsukigime Ranko's Longest Day      PS3  2014.0     Action   
15939  Batman: A Telltale Game Series      PS3  2016.0  Adventure   
16053                G1 Jockey 4 2008      PS3  2008.0     Sports   
16147     Hyperdimension Neptunia mk2      PS3  2011.0     Action   

                         Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
16            Take-Two Interactive      7.01      9.27      0.97         4.14   
34                      Activision      4.99      5.88      0.65         2.52   
37                      Activision      5.54      5.82      0.49         1.62   
54     Sony Computer Entertainment      2.96      4.88      0.81         2.12   
82                 Electronic Arts      1.06      5.05      0.13         2.01   
...                            ...       ...       ...       ...          ...   
15889  Sony Computer Entertainment      0.00      0.01      0.00         0.00   
15919           Namco Bandai Games      0.00      0.01      0.00         0.00   
15939               Telltale Games      0.00      0.01      0.00         0.00   
16053                   Tecmo Koei      0.00      0.01      0.00         0.00   
16147         Nippon Ichi Software      0.00      0.01      0.00         0.00   

       Global_Sales  
16            21.40  
34            14.03  
37            13.46  
54            10.77  
82             8.24  
...             ...  
15889          0.01  
15919          0.01  
15939          0.01  
16053          0.01  
16147          0.01  

[419 rows x 10 columns]

## Zad 2 

In [22]:
output = df.groupby("Genre").JP_Sales.agg("mean")[
    df.groupby("Genre").JP_Sales.agg("mean") >  df.groupby("Genre").EU_Sales.agg("mean")]

In [23]:
output.to_frame().reset_index().rename(columns = {"Genre":"Typ Gry", "JP_Sales":"Średnia sprzedaż w Japonii"})

Typ Gry  Średnia sprzedaż w Japonii
0        Puzzle                    0.099439
1  Role-Playing                    0.238293
2      Strategy                    0.073284